import os
import tempfile
import re
from typing import List
from git import Repo, Actor
from github import Github
from api.models import UpgradePlanItem

def apply_upgrades_and_create_pr(repo_url: str, plan: List[UpgradePlanItem], github_token: str) -> str:
    """
    Applies the upgrade plan to a repository, commits the changes to a new branch,
    pushes it, and creates a GitHub Pull Request.
    Returns the PR URL.
    """
    # 1. Parse repository name from URL (e.g., https://github.com/username/repo -> username/repo)
    repo_name = repo_url.replace("https://github.com/", "").replace(".git", "")
    
    # 2. Authenticate PyGithub
    gh = Github(github_token)
    gh_repo = gh.get_repo(repo_name)
    
    # 3. Create clone URL with token for Git access
    # https://x-access-token:<token>@github.com/username/repo.git
    auth_url = repo_url.replace("https://github.com/", f"https://x-access-token:{github_token}@github.com/")
    if not auth_url.endswith(".git"):
        auth_url += ".git"
        
    temp_dir = tempfile.mkdtemp()
    
    try:
        # Clone repo
        repo = Repo.clone_from(auth_url, temp_dir)
        
        # 4. Create a new branch
        import uuid
        branch_name = f"patchpilot-upgrade-{uuid.uuid4().hex[:6]}"
        new_branch = repo.create_head(branch_name)
        new_branch.checkout()
        
        # 5. Apply the updates locally
        # Currently supports basic requirements.txt logic
        req_file = os.path.join(temp_dir, "requirements.txt")
        if os.path.exists(req_file):
            _update_requirements_file(req_file, plan)
            
        # Optional: Add package.json logic here if needed for Node.js
        pkg_file = os.path.join(temp_dir, "package.json")
        if os.path.exists(pkg_file):
            _update_package_json(pkg_file, plan)
            
        # 6. Commit changes
        repo.git.add(update=True) # Adds modified files
        
        if not repo.is_dirty(untracked_files=True):
            print("No changes were made. Dependencies might already be at target versions locally.")
            return None
            
        author = Actor("PatchPilot Agent", "agent@patchpilot.ai")
        commit_msg = "chore(deps): Auto-upgrade outdated dependencies\n\nUpgraded dependencies:\n"
        for item in plan:
            commit_msg += f"- {item.dependency}: {item.from_version} -> {item.to_version}\n"
            
        repo.index.commit(commit_msg, author=author, committer=author)
        
        # 7. Push to GitHub
        origin = repo.remote(name="origin")
        origin.push(f"{branch_name}:{branch_name}")
        
        # 8. Create Pull Request
        pr_title = "Update Dependencies (Auto-Generated by PatchPilot)"
        pr_body = "This PR was generated by **PatchPilot AI**.\n\n### Upgraded Dependencies:\n"
        for item in plan:
            pr_body += f"- **{item.dependency}**: `{item.from_version}` ➡️ `{item.to_version}`\n"
            if item.breaking_changes and item.breaking_changes != "None":
                pr_body += f"  - ⚠️ *Note:* {item.breaking_changes}\n"
                
        pr = gh_repo.create_pull(
            title=pr_title,
            body=pr_body,
            head=branch_name,
            base=gh_repo.default_branch
        )
        
        return pr.html_url
        
    except Exception as e:
        print(f"Error executing upgrade and PR: {e}")
        raise e

def _update_requirements_file(filepath: str, plan: List[UpgradePlanItem]):
    with open(filepath, "r") as f:
        lines = f.readlines()
        
    new_lines = []
    for line in lines:
        updated_line = line
        # Simple match for dependency updates
        # e.g., fastapi==0.75.0 or fastapi>=0.75.0
        for item in plan:
            clean_line = line.split(";")[0].split("#")[0].strip()
            # Match strictly package name with optional version constraint e.g. "pandas" or "pandas >= 1.0"
            if re.match(fr"^{re.escape(item.dependency)}(?:[\s]*[=><~]+.*)?$", clean_line, re.IGNORECASE):
                updated_line = f"{item.dependency}=={item.to_version}\n"
                break
        new_lines.append(updated_line)
        
    with open(filepath, "w") as f:
        f.writelines(new_lines)

def _update_package_json(filepath: str, plan: List[UpgradePlanItem]):
    import json
    try:
        with open(filepath, "r") as f:
            data = json.load(f)
            
        changed = False
        deps_dict = data.get("dependencies", {})
        dev_deps_dict = data.get("devDependencies", {})
        
        for item in plan:
            # Handle standard deps
            if item.dependency in deps_dict:
                # Retain the prefix like ^ or ~ if present
                prefix = ""
                if deps_dict[item.dependency].startswith("^"): prefix = "^"
                elif deps_dict[item.dependency].startswith("~"): prefix = "~"
                deps_dict[item.dependency] = f"{prefix}{item.to_version}"
                changed = True
            
            # Handle dev deps
            if item.dependency in dev_deps_dict:
                prefix = ""
                if dev_deps_dict[item.dependency].startswith("^"): prefix = "^"
                elif dev_deps_dict[item.dependency].startswith("~"): prefix = "~"
                dev_deps_dict[item.dependency] = f"{prefix}{item.to_version}"
                changed = True
                
        if changed:
            with open(filepath, "w") as f:
                json.dump(data, f, indent=2)
    except Exception as e:
        print(f"Error updating package.json: {e}")
